### ISSUE TITLE
Is there a way to increase the performance of Writng EPC ? at the moment it takes 7 sec to write 2 bytes

### ISSUE THREAD

**Issue by Krishna-de** [jence/j4210u-app#23]

**Comment by jence** [comment]
Yes, it is possible to write the entire EPC at once instead of 2 bytes at a time. So, the entire 12 byte EPC can be written into the tag at once in less than 7 sec. The only thing that is needed is a bigger antenna and strong, which is found in our recently released J4220UX device also sold at Amazon (https://www.amazon.com/dp/B0CGZJSXS6). J4210U can also write the whole EPC at once after several retries. We will need to update the dll/so/dylib to add this functionality. I will inform you when this function will be added.
Regards,
Mansur.

**Comment by Krishna-de** [comment]
Thanks for Update. could you send me Project Manager or Engineer Mobile contact? I have few technical questions. Here is my email gsrk.au@gmail.com

**Comment by jence** [comment]
You can contact us using Skype id jence.com
Our general contact for jence.com is +880 1776196372 and +880 1792494877. Both are international dialing numbers.
We don't use Facebook because the owner does not like it. We can create Zoom meeting at a time of your convenience.
I can arrange a zoom meeting with you to speak to our team, including project manager.
We are closed on Fridays and Saturday. Sunday - Thursday, we are open.

Our Project Manager will send you his contact info to the email you sent us. My email is mansur@jence.com
Regards,
Mansur

**Comment by jence** [comment]
We have increased the speed of writing significantly. Several methods have been added:
InventoryOne (returns single tag inventory)
WriteEPC (writes entire 12 byte EPC in a single write instead of 2 bytes at a time)
The new version have been committed.
Regards,
Mansur
